/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sglr_SGLRInvoker */

#ifndef _Included_sglr_SGLRInvoker
#define _Included_sglr_SGLRInvoker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sglr_SGLRInvoker
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sglr_SGLRInvoker_initialize
  (JNIEnv *, jobject);

/*
 * Class:     sglr_SGLRInvoker
 * Method:    parse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sglr_SGLRInvoker_parse
  (JNIEnv *, jobject);

/*
 * Class:     sglr_SGLRInvoker
 * Method:    getResultData
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_sglr_SGLRInvoker_getResultData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
